% load("2_1.mat")

nScenarios = numel(envData.scenarios);

figure('Name','Scenario Visualization','Position',[100 100 1200 500]);

for s = 1:nScenarios
    scenario = envData.scenarios(s);
    map = scenario.map;
    routes = scenario.routes;

    subplot(1, nScenarios, s);
    imagesc(map);
    colormap gray;
    axis equal tight;
    hold on;

    title(sprintf('Map %d (%d routes)', s, numel(routes)));

    for r = 1:numel(routes)
        start = routes(r).start;
        goal  = routes(r).goal;

        % world → map indices
        sx = start(2) / envData.res;
        sy = start(1) / envData.res;
        gx = goal(2)  / envData.res;
        gy = goal(1)  / envData.res;

        % main direction
        plot(sx, sy, 'go', 'MarkerSize', 8, 'MarkerFaceColor', 'g');
        plot(gx, gy, 'r*', 'MarkerSize', 10, 'LineWidth', 1.5);

        quiver( ...
            sx, sy, ...
            gx - sx, gy - sy, ...
            0, ...
            'Color','r', ...
            'LineWidth',1.5, ...
            'MaxHeadSize',0.5);

        % flipped direction (dashed)
        quiver( ...
            gx, gy, ...
            sx - gx, sy - gy, ...
            0, ...
            'Color','m', ...
            'LineStyle','--', ...
            'LineWidth',1.2, ...
            'MaxHeadSize',0.4);

        % route label
        % text( ...
        %     (sx+gx)/2, (sy+gy)/2, ...
        %     sprintf('R%d', r), ...
        %     'Color','w', ...
        %     'FontWeight','bold', ...
        %     'FontSize',9, ...
        %     'HorizontalAlignment','center');
    end

    legend( ...
        {'Start','Goal','Route','Flipped'}, ...
        'TextColor','w', ...
        'Location','bestoutside');

    hold off;
end
